# Generated by Django 3.2.8 on 2021-10-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211024_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='title',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='data',
            name='black_data',
        ),
        migrations.RemoveField(
            model_name='data',
            name='blue_data',
        ),
        migrations.RemoveField(
            model_name='data',
            name='green_data',
        ),
        migrations.RemoveField(
            model_name='data',
            name='red_data',
        ),
        migrations.AddField(
            model_name='data',
            name='aapl_open',
            field=models.DecimalField(blank=True, decimal_places=100, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='appl_adjusted',
            field=models.DecimalField(blank=True, decimal_places=100, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='appl_close',
            field=models.DecimalField(blank=True, decimal_places=100, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='appl_high',
            field=models.DecimalField(blank=True, decimal_places=100, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='appl_low',
            field=models.DecimalField(blank=True, decimal_places=100, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='appl_volume',
            field=models.DecimalField(blank=True, decimal_places=100, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='direction',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='dn',
            field=models.DecimalField(blank=True, decimal_places=100, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='mavg',
            field=models.DecimalField(blank=True, decimal_places=100, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='up',
            field=models.DecimalField(blank=True, decimal_places=100, max_digits=100, null=True),
        ),
    ]
