# Generated by Django 3.2.8 on 2021-10-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211024_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='aapl_open',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='appl_adjusted',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='appl_close',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='appl_high',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='appl_low',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='appl_volume',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='dn',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='mavg',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='up',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=100, null=True),
        ),
    ]
