# Generated by Django 3.2.8 on 2021-10-25 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211024_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='aapl_open',
            new_name='appl_open',
        ),
    ]
